### ISSUE TITLE
Library linking error when using "cmake -Bbuild -H."

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#1]
When using "```cmake -Bbuild -H.```" instead of "```cmake .```", there is a library linking error that cannot find ```libant-message``` and ```libant-cmfw```.
I guess that it is because of ambiguous path settings in ```CMakeLists.txt``` of ```app-api```.
```
redcarrottt@tegra-carrot:~/ant-ml$ cmake .
redcarrottt@tegra-carrot:~/ant-ml/build$ make
[  2%] Make out directory
[  2%] Built target out-dir
[  4%] Built target DeviceController
[  6%] Built target TmpControl
[  8%] Built target BluetoothCommPort
[ 11%] Built target WifiDirectCommPort
[ 13%] Built target CommRawPacket
[ 17%] Built target ant-cmfw
[ 37%] Built target ant-message
[ 44%] Built target miniunz
[ 55%] Built target ant-appcore
[ 75%] Built target ant-camera
[ 86%] Built target ant-sensor
[ 86%] Built target nil
[ 88%] Building NIL for App API
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@4.0.0 | linux | arm64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/redcarrottt/ant-ml/api/app/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/redcarrottt/.node-gyp/4.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/redcarrottt/.node-gyp/4.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/redcarrottt/ant-ml/api/app',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@4.0.0 | linux | arm64
gyp  SOLINK_MODULE(target) Release/obj.target/app-api.node
 info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
/usr/bin/ld: cannot find -lant-cmfw
/usr/bin/ld: cannot find -lant-message
collect2: error: ld returned 1 exit status
app-api.target.mk:138: recipe for target 'Release/obj.target/app-api.node' failed
make[3]: *** [Release/obj.target/app-api.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.96-tegra
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/redcarrottt/ant-ml/api/app
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
api/app/CMakeFiles/nil-appsys.dir/build.make:57: recipe for target 'api/app/CMakeFiles/nil-appsys' failed
make[2]: *** [api/app/CMakeFiles/nil-appsys] Error 1
CMakeFiles/Makefile2:736: recipe for target 'api/app/CMakeFiles/nil-appsys.dir/all' failed
make[1]: *** [api/app/CMakeFiles/nil-appsys.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sinban04** [comment]
Now, we can build ANT with 
```
$ cd {ANT_ROOT_DIR}
$ mkdir build
$ cd build
$ cmake ..
$ make
```
#35 #39
