### ISSUE TITLE
Bug on connection monitoring of ANT companion app

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#156]
There is a bug that ANT companion app fails to monitor disconnection.

In this situation, following log occurs on Android Logcat.
```
2019-11-26 21:48:39.499 12333-13482/skku.eslab.ant.companion E/test: http request: http://192.168.0.33:8001/runtime/currentApp/state / GET / null
2019-11-26 21:48:39.517 12333-13482/skku.eslab.ant.companion W/System.err: java.net.ConnectException: Connection refused
2019-11-26 21:48:39.519 12333-13482/skku.eslab.ant.companion W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
2019-11-26 21:48:39.519 12333-13482/skku.eslab.ant.companion W/System.err:     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
2019-11-26 21:48:39.519 12333-13482/skku.eslab.ant.companion W/System.err:     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at java.net.Socket.connect(Socket.java:586)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:196)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
2019-11-26 21:48:39.520 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
2019-11-26 21:48:39.521 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
2019-11-26 21:48:39.521 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
2019-11-26 21:48:39.521 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
2019-11-26 21:48:39.521 12333-13482/skku.eslab.ant.companion W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
2019-11-26 21:48:39.521 12333-13482/skku.eslab.ant.companion W/System.err:     at skku.eslab.ant.companion.ConnectionManager$1.run(ConnectionManager.java:77)
2019-11-26 21:48:39.521 12333-13482/skku.eslab.ant.companion W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
2019-11-26 21:48:39.522 12333-13482/skku.eslab.ant.companion W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-11-26 21:48:39.522 12333-13482/skku.eslab.ant.companion W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-11-26 21:48:39.522 12333-13482/skku.eslab.ant.companion W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by RedCarrottt** [comment]
It is fixed according to PR #157. I close this issue.
